Add mobile
alwaysbegrowing/arbor-frontend pull request #101
Opened 2022-12-18 00:37 UTC by Bookcliff

Fixed styling so that it is order compatible.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/99197390/208271441-8686f3b8-b66f-4c3a-96af-a5600d4a2fca.png">

<img width="373" alt="image" src="https://user-images.githubusercontent.com/99197390/208271445-f8dd4907-50af-4a61-8a49-0876feac3c5c.png">

<img width="401" alt="image" src="https://user-images.githubusercontent.com/99197390/208271449-f5fe7531-0065-4b8a-9ca7-9cca699801db.png">

<img width="353" alt="image" src="https://user-images.githubusercontent.com/99197390/208271489-2e947a20-e21e-4c96-a274-2f91bc8209dd.png">

<img width="374" alt="image" src="https://user-images.githubusercontent.com/99197390/208271493-1dd4d0e5-8b65-4c4a-a994-dba71b4793bf.png">

- [ ] Fixed offerings table, auction, bond table, and bonds pages
- [ ] Auction and bonds pages headings spacing is bad. I tried different things with the flexboxes, but the only solution I came up with that looked good was the negative margin. Let me know if you find a better solution.
- [ ] Checked impact of styling on different screen sizes
- [ ] Checked that the changes don't make any breaks
- [ ] Turned off graph and tour features as they aren't conducive to the mobile set-up

2022-12-19 15:54 UTC, Namaskar-1F64F requested changes
Looks good and seems more mobile friendly 

Anything that's commented out should be deleted instead. 

using tailwind is preferred over using state to handle mobile-ness

2022-12-19 15:54 UTC, Namaskar-1F64F commented on src/components/auction/AuctionBody/index.tsx
> +            <div className={isMobile ? 'hidden' : ''}>
these should be using tailwind breakpoints. 
https://tailwindcss-v0.netlify.app/docs/responsive-design/

https://tailwindcss.com/docs/screens

it'll be something like `className="visible md:hidden"`

2022-12-19 15:54 UTC, Namaskar-1F64F commented on src/components/auctions/Table/index.tsx
> +  const menuToggle = () => {
this isn't used

2022-12-19 16:38 UTC, Bookcliff commented on src/components/auction/AuctionBody/index.tsx
> +            <div className={isMobile ? 'hidden' : ''}>
When I tried that, hidden vs. visible isn't a tailwind option unfortunately. So, when you follow tailwinds way of doing it, it doesn't move the rest of the cards to fill the space that is typically occupied by the tour card leaving a large black space.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/99197390/208475128-7d1badd0-7290-4f2f-8301-e96611eb18a7.png">


With the state, we can use 'hidden' which moves the boxes to cover the hidden space.

2022-12-19 16:43 UTC, Bookcliff commented
Removed commented out code.

Were you able to look into the bond and auction details header to see if there is a better way to fix the spacing?

2022-12-19 16:44 UTC, Bookcliff commented on src/components/auctions/Table/index.tsx
> +  const menuToggle = () => {
Fixed

2022-12-20 21:05 UTC, Namaskar-1F64F reviewed
looks good. i don't know about the auction margin top-ness. seems fine for now.

2022-12-20 21:05 UTC, Namaskar-1F64F commented on src/components/auction/Orderbook/index.tsx
> +  useEffect(() => {
Can you also remove this? I feel like you can do something similar with hiding for mobile screens with tailwind.

2022-12-20 21:05 UTC, Namaskar-1F64F commented on src/components/auctions/Table/index.tsx
> +  const [menuVisible, setMenuVisible] = useState(false)
why is this added?

2022-12-20 22:51 UTC, Bookcliff commented on src/components/auctions/Table/index.tsx
> +  const [menuVisible, setMenuVisible] = useState(false)
Removed

2022-12-20 22:52 UTC, Bookcliff commented on src/components/auction/Orderbook/index.tsx
> +  useEffect(() => {
Removed and changed so that the buttons are hidden on mobile.

2022-12-21 17:43 UTC, Namaskar-1F64F commented
![image](https://user-images.githubusercontent.com/7458951/208961574-28face46-5a86-4ffa-a682-cc0d29d09aa2.png)
the orderbook is on and the list is off for mobile.

2022-12-21 20:03 UTC, Namaskar-1F64F approved these changes
lgtm!

2022-12-21 20:03 UTC, merged