Gnosis safe
alwaysbegrowing/arbor-frontend pull request #129
Opened 2023-01-19 22:46 UTC by Bookcliff

https://www.loom.com/share/55c6f52cc55646f592091313e11ce84c

- [x] Bond can be created with pending approval
- [x] Auction can be created with pending approval
- [ ] Promissory note & auction can be created with pending bond creation

Issues #10  and #25  will be addressed in another PR

2023-01-23 12:18 UTC, Namaskar-1F64F requested changes
left some comments. looking good overall

2023-01-23 12:18 UTC, Namaskar-1F64F commented on src/components/ProductCreate/BondActionSteps.tsx
> +              tip="Bypass the approval process if the token approval has been scheduled in a previous transaction and is queued. IMPORTANT: Since the tokens have yet to be approved, gas will be autom
This surely needs to be in a separate component as it's used twice.

2023-01-23 12:18 UTC, Namaskar-1F64F commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +        .getTransactionCount('0xBE9A5b24dbEB65b21Fc91BD825257f5c4FE9c01D')
use the bond factory constant

2023-01-23 12:18 UTC, Namaskar-1F64F commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +  const from = '0xbe9a5b24dbeb65b21fc91bd825257f5c4fe9c01d'
same thing with this. this doesn't work with mainnet either, right?

2023-01-23 12:18 UTC, Namaskar-1F64F commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +  if (scheduled === true) {
```suggestion
  if (scheduled) {
```

2023-01-23 12:18 UTC, Namaskar-1F64F commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +  const [n, setN] = useState(0)
I think this should be initialized to null and later checked if there is a value other than null. is 0 a valid nonce? if it is, the failure state may go through

2023-01-23 12:18 UTC, Namaskar-1F64F commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +    const bondAddress = getContractAddress({ from, nonce })
cool, so this is to get the future bond address when it's scheduled?

2023-01-23 15:22 UTC, Bookcliff commented on src/components/CreditEnhancers/promissory/scheduledBondModal.tsx
> +                  Create a{' '}
Fixed

2023-01-23 15:54 UTC, Bookcliff commented on src/components/OfferingCreate/auction/ActionSteps.tsx
> +    if (scheduled) {
Fixed

2023-01-23 16:32 UTC, Bookcliff commented on src/components/OfferingCreate/auction/StepOne.tsx
> +    if (walletType === '"safe"') {
Fixed

2023-01-23 16:32 UTC, Bookcliff commented on src/components/OfferingCreate/auction/StepOne.tsx
> +  }, [tip, walletType])
Fixed

2023-01-23 16:38 UTC, Bookcliff commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +  const [n, setN] = useState(0)
Fixed

2023-01-23 16:44 UTC, Bookcliff commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +        .getTransactionCount('0xBE9A5b24dbEB65b21Fc91BD825257f5c4FE9c01D')
Fixed

2023-01-23 16:45 UTC, Bookcliff commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +  if (scheduled === true) {
Fixed

2023-01-23 16:45 UTC, Bookcliff commented on src/components/ProductCreate/selectors/CollateralTokenSelector.tsx
> +    const bondAddress = getContractAddress({ from, nonce })
Yep

2023-01-23 16:46 UTC, Bookcliff commented on src/components/CreditEnhancers/promissory/StepOne.tsx
> +            {walletType === '"safe"' && (
No I think it is just if the wallet type is a gnosis safe. This variable is set through wagmi, not us

2023-01-25 19:27 UTC, Bookcliff commented on src/components/ProductCreate/BondActionSteps.tsx
> +              tip="Bypass the approval process if the token approval has been scheduled in a previous transaction and is queued. IMPORTANT: Since the tokens have yet to be approved, gas will be autom
Fixed with your most recent merge

2023-01-26 14:10 UTC, Namaskar-1F64F commented
this looks good, can you merge main into this and I think it's good to go. I added a fix for the regular wallet working with a scheduled transaction. It seemed to fail before. Might be worth testing the whole flow again. 

Also, should there be a way to clear the saved bond?

2023-01-26 14:13 UTC, Namaskar-1F64F approved these changes

2023-01-26 15:32 UTC, Bookcliff commented
> Also, should there be a way to clear the saved bond?

I didn't think it was needed because if a user creates a new bond it will replace the saved bond. This also won't interfere with them selecting an already created bond, so I don't really see a reason for a user needing to clear the bond.

2023-01-28 07:51 UTC, merged

2023-01-28 07:51 UTC, Namaskar-1F64F commented
thanks for this! looks great