Add Auction Tour
alwaysbegrowing/arbor-frontend pull request #89
Opened 2022-12-15 22:38 UTC by Namaskar-1F64F

2022-12-15 22:46 UTC, RusseII approved these changes

2022-12-15 22:46 UTC, RusseII commented on src/components/auction/AuctionBody/index.tsx
> +  const bondInformationRef = createRef<HTMLDivElement>()
wow haven't seen this very often!

2022-12-15 22:46 UTC, RusseII commented on src/components/auction/AuctionTour/index.tsx
> +                href="https://docs.arbor.finance"
link to auction page probably

2022-12-16 03:15 UTC, RusseII requested changes
does not work on smaller screen sizes :(

2022-12-16 03:24 UTC, Namaskar-1F64F commented on src/components/auction/AuctionTour/index.tsx
> +                href="https://docs.arbor.finance"
the walkthrough link is right under it which links to the auction page

2022-12-16 15:19 UTC, merged